### ISSUE TITLE
No mention of dependency https://github.com/thomasloven/lovelace-card-tools

### ISSUE THREAD

**Issue by DonLuigi** [BWilky/viewtimeout#8]
Hello.

Spent great deal of time figuring out why this addon doesn't work on my HA, only to find out it needs https://github.com/thomasloven/lovelace-card-tools. Yet this fact is not mentioned anywhere in the readme.

Anyway, great work.
Thank you so much,
Ludvik

**Comment by bonstio** [comment]
Thanks for filing this bug. It helped me.
